
cpp_files = main.cpp Quadrotor.cpp Brain.cpp Attitude.cpp FDA.cpp Position.cpp Plant.cpp Command.cpp Telem.cpp


all:
	g++ ${cpp_files} -g -o quad -I. -I../../math/src -L../../math -lmath -Wall -std=c++0x





